# Based on src/bootstrap/defaults/bootstrap.dists.toml

[build]
host = [ "aarch64-apple-darwin" ]
target = [ "x86_64-apple-darwin", "aarch64-apple-darwin" ]
docs = false
extended = false

### In case of using custom built Rust, uncomment and modify these line
rustc = "bootstrap/1.74.0-custom-crosscompiling/bin/rustc"
cargo = "bootstrap/1.74.0-custom-crosscompiling/bin/cargo"

submodules = false
# tools = [ "cargo" ]
# cargo-native-static = true

[llvm]
download-ci-llvm = false
# libzstd = false
static-libstdcpp = true
# targets = "X86"
targets = "X86;AArch64"
experimental-targets = ""


[rust]
channel = "dev"
optimize = "s"
codegen-tests = false

[install]
prefix = "build/1.75.0-custom-crosscompiling"
sysconfdir = "etc"
