name: Download cached LLVM

on:
  push:
    branches:
      - '*'

jobs:
  job0_buildjob:
    name: Build job
    runs-on: macos-15
    if: ${{ contains(github.event.head_commit.message, 'DOWNLOADCACHEDLLVM') }}
    steps:
      - name: Restore cached LLVM 20 (Rust 1.87-1.90)
        id: cache-llvm-restore
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0 (27/6/2026)
        with:
          key: ${{ runner.os }}-llvm20-${{ github.run_id }}
          path: |
            build/aarch64-apple-darwin/llvm
          restore-keys:
            ${{ runner.os }}-llvm20
      
      - name: Zip cached LLVM
        run: zip -qr cached-llvm-20.zip build

      - name: Upload zipped LLVM
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with: 
          archive: false
          path: ./cached-llvm-20.zip