name: Download firmware for Fortigate 200E

on:
  workflow_dispatch:

jobs:
  download:
    name: Download
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: |
          wget https://dl.ressis.ir:8080/Firmwares/FortiGate/v7/7.2/7.2.11/FGT_200E-v7.2.11.M-build1740-FORTINET.out.zip
      
      - name: Upload to artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          archive: false
          path: *.zip
